default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV['APPLE_API_KEY_ID'],
      issuer_id: ENV['APPLE_ISSUER_ID'],
      key_content: ENV['APPLE_API_KEY_P8']
    )
    upload_to_testflight(
      api_key: api_key,
      ipa: '../build/ios/ipa/kamili_social.ipa',
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy to App Store"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV['APPLE_API_KEY_ID'],
      issuer_id: ENV['APPLE_ISSUER_ID'],
      key_content: ENV['APPLE_API_KEY_P8']
    )
    upload_to_app_store(
      api_key: api_key,
      ipa: '../build/ios/ipa/kamili_social.ipa',
      submit_for_review: false
    )
  end
end
